spring.datasource.url=jdbc:postgresql://postgres:5432/proyectopresupuesto
spring.datasource.username=proyectopresupuesto
spring.datasource.password=proyectopresupuesto

spring.flyway.url=jdbc:postgresql://postgres:5432/proyectopresupuesto
spring.flyway.user=proyectopresupuesto
spring.flyway.password=proyectopresupuesto
